import 'dart:ui';

const Color kPrimaryColor = Color(0xFF6CC51D);
const Color kPrimaryColor2 = Color(0xFF5ADB32);
const Color kDarkPrimaryColor = Color(0xFF2A8C0C);
const Color kMiddlePrimaryColor = Color(0xFF458D00);
const Color kDarkPrimaryColor1 = Color(0xFF295429);
const Color kBgColor = Color(0xFFFAFBFC);
const Color kWhiteColor = Color(0xFFFFFFFF);
const Color kWhiteColor2 = Color(0xFFF1F1F1);
const Color kBlackColor = Color(0xFF000000);
const Color kBlackTextColor = Color(0xFF1A1C1E);
const Color kBlackTextColor2 = Color(0xFF202224);
const Color kBlackTextColor3 = Color(0xFF262F3D);
const Color kGreyColor = Color(0xFFB9B9B9);
const Color kGreyShade1Color = Color(0xFF535353);
const Color kGreyShade2Color = Color(0xFFEDF1F3);
const Color kGreyShade3Color = Color(0xFFD5D5D5);
const Color kGreyShade5Color = Color(0xFF979797);
const Color kGreyShade6Color = Color(0xFF343A40);
const Color kGreyShade7Color = Color(0xFF737791);
const Color kGreyShade8Color = Color(0xFFD0D5DD);
const Color kGreyShade9Color = Color(0xFF667085);
const Color kGreyShade10Color = Color(0xFF9B9B9B);
const Color kRedColor = Color(0xFFFF0000);
const Color kYellowColor = Color(0xFFE8AD41);
const Color kYellowColor1 = Color(0xFFFAA524);
const Color kYellowColor2 = Color(0xFFFCDFB3);
const Color kPurpleShadeColor = Color(0xFFB6BFE8);

const Color kBorderColor = Color(0xFFCBCDCE);
const Color kBorderColor2 = Color(0xFFC2C6CE);
const Color kBorderColor3 = Color(0xFFCED4DA);
const Color kBorderColor4 = Color(0xFFE3E3E7);
const Color kBorderColor5 = Color(0xFFE1E2E9);
const Color kBlueColor = Color(0xFF151D48);
const Color kDarkBlueColor = Color(0xFF1D1F2C);
const Color kLightBlueColor = Color(0xFF7B91B0);
const Color kCreamColor = Color(0xFFFAFBFD);
const Color kCreamColor2 = Color(0xFFF2F2F2);
const Color kCreamColor3 = Color(0xFFFDFDFD);
const Color kAmberColor = Color(0xFFFFC107);
const Color kBarColor = Color(0xFFF6F6F6);
const Color kDisableBtnTextColor = Color(0xFFADB5BD);
const Color kDisableButtonColor = Color(0xFFE9ECEF);

